### ISSUE TITLE
Error: configuration param 'bookmark-history-menu' not declared in the schema

### ISSUE THREAD

**Issue by leibovic** [mozilla-services/switchboard-server#8]
I'm running into this error trying to run the server locally:

```
[leibovic@margaret-mbp:~/code/switchboard-sever]$ CONFIG_FILE=../switchboard-experiments/experiments.json node index.js
/Users/leibovic/code/s-s/node_modules/convict/lib/convict.js:417
        throw new Error(errBuf);
        ^

Error: configuration param 'bookmark-history-menu' not declared in the schema
configuration param 'search-term' not declared in the schema
    at Object.rv.validate (/Users/leibovic/code/s-s/node_modules/convict/lib/convict.js:417:15)
    at Object.<anonymous> (/Users/leibovic/code/s-s/lib/config.js:80:8)
    at Module._compile (module.js:434:26)
    at normalLoader (/Users/leibovic/code/s-s/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/leibovic/code/s-s/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/leibovic/code/s-s/lib/app.js:10:28)
```

**Comment by milescrabill** [comment]
This error comes from passing an EXPERIMENTS_FILE in place of a CONFIG_FILE. Those params not declared in the schema are not the same ones the config file uses, so convict rightly rejects them. You should have a CONFIG_FILE following the model of https://github.com/mozilla-services/switchboard-server/blob/master/config/example_config.json. Sorry for the opaqueness of that!
